"""message=initial

Revision ID: cf7f01cf6d0c
Revises: d929141eb648
Create Date: 2026-02-22 12:37:59.201041

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf7f01cf6d0c"
down_revision: str | Sequence[str] | None = "d929141eb648"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "qualification", sa.Enum("nurse", "associate_nurse", "midwife", name="qualification"), nullable=False
        ),
        sa.Column("employment_type", sa.Enum("full_time", "part_time", name="employmenttype"), nullable=False),
        sa.Column("max_night_shifts", sa.Integer(), nullable=False),
        sa.Column("night_shift_deduction_balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pediatric_doctor_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("status", sa.Enum("draft", "published", name="schedulestatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year_month"),
    )
    op.create_table(
        "member_capabilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column(
            "capability_type",
            sa.Enum(
                "outpatient_leader",
                "ward_leader",
                "night_leader",
                "day_shift",
                "night_shift",
                "beauty",
                "mw_outpatient",
                "ward_staff",
                "rookie",
                name="capabilitytype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ng_pairs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("member_id_1", sa.Integer(), nullable=False),
        sa.Column("member_id_2", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("member_id_1 < member_id_2", name="ck_ng_pairs_ordering"),
        sa.ForeignKeyConstraint(["member_id_1"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id_2"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id_1", "member_id_2", name="uq_ng_pairs_members"),
    )
    op.create_table(
        "shift_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "shift_type",
            sa.Enum(
                "outpatient_leader",
                "treatment_room",
                "beauty",
                "mw_outpatient",
                "ward_leader",
                "ward",
                "delivery",
                "delivery_charge",
                "night_leader",
                "night",
                "day_off",
                name="shifttype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "date", name="uq_shift_assignments_member_date"),
    )
    op.create_table(
        "shift_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "date", name="uq_shift_requests_member_date"),
    )
    op.drop_index(op.f("email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("email"), "users", ["email"], unique=True)
    op.drop_table("shift_requests")
    op.drop_table("shift_assignments")
    op.drop_table("ng_pairs")
    op.drop_table("member_capabilities")
    op.drop_table("schedules")
    op.drop_table("pediatric_doctor_schedules")
    op.drop_table("members")
    # ### end Alembic commands ###
